swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
schemes:
- https
paths:
  /ingridients:
    get:
      summary: Returns a list of all ingridients
  /ingridients/{id}:
    get:
      summary: Returns a description of selected ingridient
  /ingdridients/add:
    post:
      summary: Add one ingridient
  /dish:
    get:
      summary: Returns all dishes.
      description: Returns a list of all dishes for user.
      produces:
        - application/json
      responses:
        200:
          description: OK
  /dish/add:
    post:
      summary: Add new dish
      parameters:
      - name: dish_name
        in: body
        required: true
        schema:
          type: object
          required:
          - dish_name
          properties:
            dish_name:
              type: string
      responses:
        '200':
          description: Company was added successfully.
  /dish/edit:
    put:
      summary: Edits selected dish.
  /dish/delete:
    delete:
      summary: Delete selected dish.
  /menu/{period}:
    get:
      summary: Returns dishes for selected period.
      description: Returns dishes for selected period.
      produces:
      - application/json
      responses:
        200:
          description: OK
  /menu/ingredients/{period}:
    get:
      summary: Returns ingridients.
      description: Returns a list of total ingridients.
      produces:
      - application/json
      responses:
        200:
          description: OK
