# Generated by Django 2.2.1 on 2019-08-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_recipe_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day2meal',
            name='date',
            field=models.DateField(),
        ),
    ]
