# Generated by Django 2.2.1 on 2019-08-11 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_auto_20190811_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day2meal',
            name='meal_name',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_app.Day2Meal'),
        ),
    ]
