# Generated by Django 2.2.4 on 2019-08-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0005_auto_20190811_1037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meal2Dish',
        ),
    ]
