# Generated by Django 2.2 on 2019-04-17 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=30)),
                ('ingredient_desc', models.CharField(max_length=200)),
                ('ingredient_measure', models.CharField(choices=[('g', 'Gramme'), ('ml', 'Milliliter')], default='g', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=50)),
                ('recipe_desc', models.CharField(max_length=200)),
                ('recipe_persons', models.PositiveIntegerField(default=1, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=50)),
                ('dish_desc', models.CharField(max_length=200)),
                ('dish_persons', models.PositiveIntegerField(default=1, max_length=2)),
                ('dish_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_app.Recipes')),
            ],
        ),
        migrations.CreateModel(
            name='Compositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition_name', models.CharField(max_length=50)),
                ('recipe_desc', models.CharField(max_length=200)),
                ('ingredient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_app.Ingredients')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_app.Recipes')),
            ],
        ),
    ]
