# Generated by Django 2.2 on 2019-04-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='dish_persons',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='recipe_persons',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
