# Generated by Django 2.2.1 on 2019-08-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_meal_meal_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
