# Generated by Django 2.2 on 2019-04-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_auto_20190429_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compositions',
            name='recipe_desc',
        ),
        migrations.AddField(
            model_name='compositions',
            name='ingredient_amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
