# Generated by Django 2.2.1 on 2019-05-06 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_auto_20190430_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compositions',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipes',
            name='compositions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food_app.Compositions'),
            preserve_default=False,
        ),
    ]
