# Generated by Django 2.2 on 2019-05-17 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_auto_20190506_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='compositions',
        ),
        migrations.AddField(
            model_name='compositions',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food_app.Recipes'),
        ),
    ]
