# Generated by Django 2.2 on 2019-05-17 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0005_auto_20190517_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositions',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food_app.Ingredients'),
        ),
    ]
